AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  data-store

  Sample SAM Template for data-store

Resources:
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  TableParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /global/dataStoreTableArn
      Type: String
      Value: !GetAttr Table.Arn

  GraphQLDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: "{{resolve:ssm:/global/apiId}}"
      DynamoDBConfig:
        TableName: !Ref Table
        AwsRegion: !Ref AWS::Region
      Type: AMAZON_DYNAMODB
      Name: dynamodbds
